/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterSchoolRouteImport } from './routes/register-school'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSurveyRouteImport } from './routes/_authenticated/survey'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/_superadmin'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as SchoolsSchoolIdSignupRouteImport } from './routes/schools.$schoolId.signup'
import { Route as AuthenticatedChallengesMySuggestionsRouteImport } from './routes/_authenticated/challenges.my-suggestions'
import { Route as AuthenticatedChallengesIdRouteImport } from './routes/_authenticated/challenges.$id'
import { Route as AuthenticatedSuperadminAdminRouteImport } from './routes/_authenticated/_superadmin/admin'
import { Route as AuthenticatedAdminSchoolRouteImport } from './routes/_authenticated/_admin/school'
import { Route as AuthenticatedSuperadminAdminIndexRouteImport } from './routes/_authenticated/_superadmin/admin.index'
import { Route as AuthenticatedSuperadminAdminUsersRouteImport } from './routes/_authenticated/_superadmin/admin.users'
import { Route as AuthenticatedSuperadminAdminUpdatesRouteImport } from './routes/_authenticated/_superadmin/admin.updates'
import { Route as AuthenticatedSuperadminAdminSurveysRouteImport } from './routes/_authenticated/_superadmin/admin.surveys'
import { Route as AuthenticatedSuperadminAdminSettingsRouteImport } from './routes/_authenticated/_superadmin/admin.settings'
import { Route as AuthenticatedSuperadminAdminSchoolsRouteImport } from './routes/_authenticated/_superadmin/admin.schools'
import { Route as AuthenticatedSuperadminAdminReportsRouteImport } from './routes/_authenticated/_superadmin/admin.reports'
import { Route as AuthenticatedSuperadminAdminMediaRouteImport } from './routes/_authenticated/_superadmin/admin.media'
import { Route as AuthenticatedSuperadminAdminInvitesRouteImport } from './routes/_authenticated/_superadmin/admin.invites'
import { Route as AuthenticatedSuperadminAdminHousesRouteImport } from './routes/_authenticated/_superadmin/admin.houses'
import { Route as AuthenticatedSuperadminAdminEventsRouteImport } from './routes/_authenticated/_superadmin/admin.events'
import { Route as AuthenticatedSuperadminAdminDeletedUsersRouteImport } from './routes/_authenticated/_superadmin/admin.deleted-users'
import { Route as AuthenticatedSuperadminAdminBadgesRouteImport } from './routes/_authenticated/_superadmin/admin.badges'
import { Route as AuthenticatedSuperadminAdminAuditLogRouteImport } from './routes/_authenticated/_superadmin/admin.audit-log'
import { Route as AuthenticatedSuperadminAdminAssemblyRouteImport } from './routes/_authenticated/_superadmin/admin.assembly'
import { Route as AuthenticatedSuperadminAdminAnalyticsRouteImport } from './routes/_authenticated/_superadmin/admin.analytics'
import { Route as AuthenticatedSuperadminAdminAllowlistRouteImport } from './routes/_authenticated/_superadmin/admin.allowlist'
import { Route as AuthenticatedAdminSchoolUsersRouteImport } from './routes/_authenticated/_admin/school.users'
import { Route as AuthenticatedAdminSchoolUpdatesRouteImport } from './routes/_authenticated/_admin/school.updates'
import { Route as AuthenticatedAdminSchoolMessagesRouteImport } from './routes/_authenticated/_admin/school.messages'
import { Route as AuthenticatedAdminSchoolLeaderboardRouteImport } from './routes/_authenticated/_admin/school.leaderboard'
import { Route as AuthenticatedAdminSchoolFeedRouteImport } from './routes/_authenticated/_admin/school.feed'
import { Route as AuthenticatedAdminSchoolEventsRouteImport } from './routes/_authenticated/_admin/school.events'
import { Route as AuthenticatedAdminSchoolAssemblyRouteImport } from './routes/_authenticated/_admin/school.assembly'
import { Route as AuthenticatedAdminSchoolActivityRouteImport } from './routes/_authenticated/_admin/school.activity'
import { Route as AuthenticatedSuperadminAdminSchoolsIndexRouteImport } from './routes/_authenticated/_superadmin/admin.schools.index'
import { Route as AuthenticatedSuperadminAdminSchoolsPendingRouteImport } from './routes/_authenticated/_superadmin/admin.schools.pending'
import { Route as AuthenticatedAdminAdminAssemblyPresentRouteImport } from './routes/_authenticated/_admin/admin_.assembly_.present'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSchoolRoute = RegisterSchoolRouteImport.update({
  id: '/register-school',
  path: '/register-school',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSurveyRoute = AuthenticatedSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/_superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SchoolsSchoolIdSignupRoute = SchoolsSchoolIdSignupRouteImport.update({
  id: '/schools/$schoolId/signup',
  path: '/schools/$schoolId/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChallengesMySuggestionsRoute =
  AuthenticatedChallengesMySuggestionsRouteImport.update({
    id: '/my-suggestions',
    path: '/my-suggestions',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)
const AuthenticatedChallengesIdRoute =
  AuthenticatedChallengesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)
const AuthenticatedSuperadminAdminRoute =
  AuthenticatedSuperadminAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedAdminSchoolRoute =
  AuthenticatedAdminSchoolRouteImport.update({
    id: '/school',
    path: '/school',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminIndexRoute =
  AuthenticatedSuperadminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminUsersRoute =
  AuthenticatedSuperadminAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminUpdatesRoute =
  AuthenticatedSuperadminAdminUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminSurveysRoute =
  AuthenticatedSuperadminAdminSurveysRouteImport.update({
    id: '/surveys',
    path: '/surveys',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminSettingsRoute =
  AuthenticatedSuperadminAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminSchoolsRoute =
  AuthenticatedSuperadminAdminSchoolsRouteImport.update({
    id: '/schools',
    path: '/schools',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminReportsRoute =
  AuthenticatedSuperadminAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminMediaRoute =
  AuthenticatedSuperadminAdminMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminInvitesRoute =
  AuthenticatedSuperadminAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminHousesRoute =
  AuthenticatedSuperadminAdminHousesRouteImport.update({
    id: '/houses',
    path: '/houses',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminEventsRoute =
  AuthenticatedSuperadminAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminDeletedUsersRoute =
  AuthenticatedSuperadminAdminDeletedUsersRouteImport.update({
    id: '/deleted-users',
    path: '/deleted-users',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminBadgesRoute =
  AuthenticatedSuperadminAdminBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminAuditLogRoute =
  AuthenticatedSuperadminAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminAssemblyRoute =
  AuthenticatedSuperadminAdminAssemblyRouteImport.update({
    id: '/assembly',
    path: '/assembly',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminAnalyticsRoute =
  AuthenticatedSuperadminAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedSuperadminAdminAllowlistRoute =
  AuthenticatedSuperadminAdminAllowlistRouteImport.update({
    id: '/allowlist',
    path: '/allowlist',
    getParentRoute: () => AuthenticatedSuperadminAdminRoute,
  } as any)
const AuthenticatedAdminSchoolUsersRoute =
  AuthenticatedAdminSchoolUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedAdminSchoolUpdatesRoute =
  AuthenticatedAdminSchoolUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedAdminSchoolMessagesRoute =
  AuthenticatedAdminSchoolMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedAdminSchoolLeaderboardRoute =
  AuthenticatedAdminSchoolLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedAdminSchoolFeedRoute =
  AuthenticatedAdminSchoolFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedAdminSchoolEventsRoute =
  AuthenticatedAdminSchoolEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedAdminSchoolAssemblyRoute =
  AuthenticatedAdminSchoolAssemblyRouteImport.update({
    id: '/assembly',
    path: '/assembly',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedAdminSchoolActivityRoute =
  AuthenticatedAdminSchoolActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminSchoolRoute,
  } as any)
const AuthenticatedSuperadminAdminSchoolsIndexRoute =
  AuthenticatedSuperadminAdminSchoolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperadminAdminSchoolsRoute,
  } as any)
const AuthenticatedSuperadminAdminSchoolsPendingRoute =
  AuthenticatedSuperadminAdminSchoolsPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedSuperadminAdminSchoolsRoute,
  } as any)
const AuthenticatedAdminAdminAssemblyPresentRoute =
  AuthenticatedAdminAdminAssemblyPresentRouteImport.update({
    id: '/admin_/assembly_/present',
    path: '/admin/assembly/present',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/register-school': typeof RegisterSchoolRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/school': typeof AuthenticatedAdminSchoolRouteWithChildren
  '/admin': typeof AuthenticatedSuperadminAdminRouteWithChildren
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/challenges/my-suggestions': typeof AuthenticatedChallengesMySuggestionsRoute
  '/schools/$schoolId/signup': typeof SchoolsSchoolIdSignupRoute
  '/school/activity': typeof AuthenticatedAdminSchoolActivityRoute
  '/school/assembly': typeof AuthenticatedAdminSchoolAssemblyRoute
  '/school/events': typeof AuthenticatedAdminSchoolEventsRoute
  '/school/feed': typeof AuthenticatedAdminSchoolFeedRoute
  '/school/leaderboard': typeof AuthenticatedAdminSchoolLeaderboardRoute
  '/school/messages': typeof AuthenticatedAdminSchoolMessagesRoute
  '/school/updates': typeof AuthenticatedAdminSchoolUpdatesRoute
  '/school/users': typeof AuthenticatedAdminSchoolUsersRoute
  '/admin/allowlist': typeof AuthenticatedSuperadminAdminAllowlistRoute
  '/admin/analytics': typeof AuthenticatedSuperadminAdminAnalyticsRoute
  '/admin/assembly': typeof AuthenticatedSuperadminAdminAssemblyRoute
  '/admin/audit-log': typeof AuthenticatedSuperadminAdminAuditLogRoute
  '/admin/badges': typeof AuthenticatedSuperadminAdminBadgesRoute
  '/admin/deleted-users': typeof AuthenticatedSuperadminAdminDeletedUsersRoute
  '/admin/events': typeof AuthenticatedSuperadminAdminEventsRoute
  '/admin/houses': typeof AuthenticatedSuperadminAdminHousesRoute
  '/admin/invites': typeof AuthenticatedSuperadminAdminInvitesRoute
  '/admin/media': typeof AuthenticatedSuperadminAdminMediaRoute
  '/admin/reports': typeof AuthenticatedSuperadminAdminReportsRoute
  '/admin/schools': typeof AuthenticatedSuperadminAdminSchoolsRouteWithChildren
  '/admin/settings': typeof AuthenticatedSuperadminAdminSettingsRoute
  '/admin/surveys': typeof AuthenticatedSuperadminAdminSurveysRoute
  '/admin/updates': typeof AuthenticatedSuperadminAdminUpdatesRoute
  '/admin/users': typeof AuthenticatedSuperadminAdminUsersRoute
  '/admin/': typeof AuthenticatedSuperadminAdminIndexRoute
  '/admin/assembly/present': typeof AuthenticatedAdminAdminAssemblyPresentRoute
  '/admin/schools/pending': typeof AuthenticatedSuperadminAdminSchoolsPendingRoute
  '/admin/schools/': typeof AuthenticatedSuperadminAdminSchoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/register-school': typeof RegisterSchoolRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/school': typeof AuthenticatedAdminSchoolRouteWithChildren
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/challenges/my-suggestions': typeof AuthenticatedChallengesMySuggestionsRoute
  '/schools/$schoolId/signup': typeof SchoolsSchoolIdSignupRoute
  '/school/activity': typeof AuthenticatedAdminSchoolActivityRoute
  '/school/assembly': typeof AuthenticatedAdminSchoolAssemblyRoute
  '/school/events': typeof AuthenticatedAdminSchoolEventsRoute
  '/school/feed': typeof AuthenticatedAdminSchoolFeedRoute
  '/school/leaderboard': typeof AuthenticatedAdminSchoolLeaderboardRoute
  '/school/messages': typeof AuthenticatedAdminSchoolMessagesRoute
  '/school/updates': typeof AuthenticatedAdminSchoolUpdatesRoute
  '/school/users': typeof AuthenticatedAdminSchoolUsersRoute
  '/admin/allowlist': typeof AuthenticatedSuperadminAdminAllowlistRoute
  '/admin/analytics': typeof AuthenticatedSuperadminAdminAnalyticsRoute
  '/admin/assembly': typeof AuthenticatedSuperadminAdminAssemblyRoute
  '/admin/audit-log': typeof AuthenticatedSuperadminAdminAuditLogRoute
  '/admin/badges': typeof AuthenticatedSuperadminAdminBadgesRoute
  '/admin/deleted-users': typeof AuthenticatedSuperadminAdminDeletedUsersRoute
  '/admin/events': typeof AuthenticatedSuperadminAdminEventsRoute
  '/admin/houses': typeof AuthenticatedSuperadminAdminHousesRoute
  '/admin/invites': typeof AuthenticatedSuperadminAdminInvitesRoute
  '/admin/media': typeof AuthenticatedSuperadminAdminMediaRoute
  '/admin/reports': typeof AuthenticatedSuperadminAdminReportsRoute
  '/admin/settings': typeof AuthenticatedSuperadminAdminSettingsRoute
  '/admin/surveys': typeof AuthenticatedSuperadminAdminSurveysRoute
  '/admin/updates': typeof AuthenticatedSuperadminAdminUpdatesRoute
  '/admin/users': typeof AuthenticatedSuperadminAdminUsersRoute
  '/admin': typeof AuthenticatedSuperadminAdminIndexRoute
  '/admin/assembly/present': typeof AuthenticatedAdminAdminAssemblyPresentRoute
  '/admin/schools/pending': typeof AuthenticatedSuperadminAdminSchoolsPendingRoute
  '/admin/schools': typeof AuthenticatedSuperadminAdminSchoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/register-school': typeof RegisterSchoolRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/survey': typeof AuthenticatedSurveyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/_authenticated/_admin/school': typeof AuthenticatedAdminSchoolRouteWithChildren
  '/_authenticated/_superadmin/admin': typeof AuthenticatedSuperadminAdminRouteWithChildren
  '/_authenticated/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/_authenticated/challenges/my-suggestions': typeof AuthenticatedChallengesMySuggestionsRoute
  '/schools/$schoolId/signup': typeof SchoolsSchoolIdSignupRoute
  '/_authenticated/_admin/school/activity': typeof AuthenticatedAdminSchoolActivityRoute
  '/_authenticated/_admin/school/assembly': typeof AuthenticatedAdminSchoolAssemblyRoute
  '/_authenticated/_admin/school/events': typeof AuthenticatedAdminSchoolEventsRoute
  '/_authenticated/_admin/school/feed': typeof AuthenticatedAdminSchoolFeedRoute
  '/_authenticated/_admin/school/leaderboard': typeof AuthenticatedAdminSchoolLeaderboardRoute
  '/_authenticated/_admin/school/messages': typeof AuthenticatedAdminSchoolMessagesRoute
  '/_authenticated/_admin/school/updates': typeof AuthenticatedAdminSchoolUpdatesRoute
  '/_authenticated/_admin/school/users': typeof AuthenticatedAdminSchoolUsersRoute
  '/_authenticated/_superadmin/admin/allowlist': typeof AuthenticatedSuperadminAdminAllowlistRoute
  '/_authenticated/_superadmin/admin/analytics': typeof AuthenticatedSuperadminAdminAnalyticsRoute
  '/_authenticated/_superadmin/admin/assembly': typeof AuthenticatedSuperadminAdminAssemblyRoute
  '/_authenticated/_superadmin/admin/audit-log': typeof AuthenticatedSuperadminAdminAuditLogRoute
  '/_authenticated/_superadmin/admin/badges': typeof AuthenticatedSuperadminAdminBadgesRoute
  '/_authenticated/_superadmin/admin/deleted-users': typeof AuthenticatedSuperadminAdminDeletedUsersRoute
  '/_authenticated/_superadmin/admin/events': typeof AuthenticatedSuperadminAdminEventsRoute
  '/_authenticated/_superadmin/admin/houses': typeof AuthenticatedSuperadminAdminHousesRoute
  '/_authenticated/_superadmin/admin/invites': typeof AuthenticatedSuperadminAdminInvitesRoute
  '/_authenticated/_superadmin/admin/media': typeof AuthenticatedSuperadminAdminMediaRoute
  '/_authenticated/_superadmin/admin/reports': typeof AuthenticatedSuperadminAdminReportsRoute
  '/_authenticated/_superadmin/admin/schools': typeof AuthenticatedSuperadminAdminSchoolsRouteWithChildren
  '/_authenticated/_superadmin/admin/settings': typeof AuthenticatedSuperadminAdminSettingsRoute
  '/_authenticated/_superadmin/admin/surveys': typeof AuthenticatedSuperadminAdminSurveysRoute
  '/_authenticated/_superadmin/admin/updates': typeof AuthenticatedSuperadminAdminUpdatesRoute
  '/_authenticated/_superadmin/admin/users': typeof AuthenticatedSuperadminAdminUsersRoute
  '/_authenticated/_superadmin/admin/': typeof AuthenticatedSuperadminAdminIndexRoute
  '/_authenticated/_admin/admin_/assembly_/present': typeof AuthenticatedAdminAdminAssemblyPresentRoute
  '/_authenticated/_superadmin/admin/schools/pending': typeof AuthenticatedSuperadminAdminSchoolsPendingRoute
  '/_authenticated/_superadmin/admin/schools/': typeof AuthenticatedSuperadminAdminSchoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/register-school'
    | '/reset-password'
    | '/achievements'
    | '/activities'
    | '/announcements'
    | '/challenges'
    | '/dashboard'
    | '/feed'
    | '/leaderboard'
    | '/profile'
    | '/survey'
    | '/auth/callback'
    | '/invite/$token'
    | '/join/$code'
    | '/school'
    | '/admin'
    | '/challenges/$id'
    | '/challenges/my-suggestions'
    | '/schools/$schoolId/signup'
    | '/school/activity'
    | '/school/assembly'
    | '/school/events'
    | '/school/feed'
    | '/school/leaderboard'
    | '/school/messages'
    | '/school/updates'
    | '/school/users'
    | '/admin/allowlist'
    | '/admin/analytics'
    | '/admin/assembly'
    | '/admin/audit-log'
    | '/admin/badges'
    | '/admin/deleted-users'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/invites'
    | '/admin/media'
    | '/admin/reports'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/updates'
    | '/admin/users'
    | '/admin/'
    | '/admin/assembly/present'
    | '/admin/schools/pending'
    | '/admin/schools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/register-school'
    | '/reset-password'
    | '/achievements'
    | '/activities'
    | '/announcements'
    | '/challenges'
    | '/dashboard'
    | '/feed'
    | '/leaderboard'
    | '/profile'
    | '/survey'
    | '/auth/callback'
    | '/invite/$token'
    | '/join/$code'
    | '/school'
    | '/challenges/$id'
    | '/challenges/my-suggestions'
    | '/schools/$schoolId/signup'
    | '/school/activity'
    | '/school/assembly'
    | '/school/events'
    | '/school/feed'
    | '/school/leaderboard'
    | '/school/messages'
    | '/school/updates'
    | '/school/users'
    | '/admin/allowlist'
    | '/admin/analytics'
    | '/admin/assembly'
    | '/admin/audit-log'
    | '/admin/badges'
    | '/admin/deleted-users'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/invites'
    | '/admin/media'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/updates'
    | '/admin/users'
    | '/admin'
    | '/admin/assembly/present'
    | '/admin/schools/pending'
    | '/admin/schools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/register-school'
    | '/reset-password'
    | '/_authenticated/_admin'
    | '/_authenticated/_superadmin'
    | '/_authenticated/achievements'
    | '/_authenticated/activities'
    | '/_authenticated/announcements'
    | '/_authenticated/challenges'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/survey'
    | '/auth/callback'
    | '/invite/$token'
    | '/join/$code'
    | '/_authenticated/_admin/school'
    | '/_authenticated/_superadmin/admin'
    | '/_authenticated/challenges/$id'
    | '/_authenticated/challenges/my-suggestions'
    | '/schools/$schoolId/signup'
    | '/_authenticated/_admin/school/activity'
    | '/_authenticated/_admin/school/assembly'
    | '/_authenticated/_admin/school/events'
    | '/_authenticated/_admin/school/feed'
    | '/_authenticated/_admin/school/leaderboard'
    | '/_authenticated/_admin/school/messages'
    | '/_authenticated/_admin/school/updates'
    | '/_authenticated/_admin/school/users'
    | '/_authenticated/_superadmin/admin/allowlist'
    | '/_authenticated/_superadmin/admin/analytics'
    | '/_authenticated/_superadmin/admin/assembly'
    | '/_authenticated/_superadmin/admin/audit-log'
    | '/_authenticated/_superadmin/admin/badges'
    | '/_authenticated/_superadmin/admin/deleted-users'
    | '/_authenticated/_superadmin/admin/events'
    | '/_authenticated/_superadmin/admin/houses'
    | '/_authenticated/_superadmin/admin/invites'
    | '/_authenticated/_superadmin/admin/media'
    | '/_authenticated/_superadmin/admin/reports'
    | '/_authenticated/_superadmin/admin/schools'
    | '/_authenticated/_superadmin/admin/settings'
    | '/_authenticated/_superadmin/admin/surveys'
    | '/_authenticated/_superadmin/admin/updates'
    | '/_authenticated/_superadmin/admin/users'
    | '/_authenticated/_superadmin/admin/'
    | '/_authenticated/_admin/admin_/assembly_/present'
    | '/_authenticated/_superadmin/admin/schools/pending'
    | '/_authenticated/_superadmin/admin/schools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterSchoolRoute: typeof RegisterSchoolRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinCodeRoute: typeof JoinCodeRoute
  SchoolsSchoolIdSignupRoute: typeof SchoolsSchoolIdSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-school': {
      id: '/register-school'
      path: '/register-school'
      fullPath: '/register-school'
      preLoaderRoute: typeof RegisterSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/survey': {
      id: '/_authenticated/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof AuthenticatedSurveyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_superadmin': {
      id: '/_authenticated/_superadmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/schools/$schoolId/signup': {
      id: '/schools/$schoolId/signup'
      path: '/schools/$schoolId/signup'
      fullPath: '/schools/$schoolId/signup'
      preLoaderRoute: typeof SchoolsSchoolIdSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/challenges/my-suggestions': {
      id: '/_authenticated/challenges/my-suggestions'
      path: '/my-suggestions'
      fullPath: '/challenges/my-suggestions'
      preLoaderRoute: typeof AuthenticatedChallengesMySuggestionsRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
    '/_authenticated/challenges/$id': {
      id: '/_authenticated/challenges/$id'
      path: '/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof AuthenticatedChallengesIdRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
    '/_authenticated/_superadmin/admin': {
      id: '/_authenticated/_superadmin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_admin/school': {
      id: '/_authenticated/_admin/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AuthenticatedAdminSchoolRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_superadmin/admin/': {
      id: '/_authenticated/_superadmin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/users': {
      id: '/_authenticated/_superadmin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/updates': {
      id: '/_authenticated/_superadmin/admin/updates'
      path: '/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminUpdatesRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/surveys': {
      id: '/_authenticated/_superadmin/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminSurveysRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/settings': {
      id: '/_authenticated/_superadmin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/schools': {
      id: '/_authenticated/_superadmin/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminSchoolsRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/reports': {
      id: '/_authenticated/_superadmin/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminReportsRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/media': {
      id: '/_authenticated/_superadmin/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminMediaRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/invites': {
      id: '/_authenticated/_superadmin/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/houses': {
      id: '/_authenticated/_superadmin/admin/houses'
      path: '/houses'
      fullPath: '/admin/houses'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminHousesRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/events': {
      id: '/_authenticated/_superadmin/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminEventsRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/deleted-users': {
      id: '/_authenticated/_superadmin/admin/deleted-users'
      path: '/deleted-users'
      fullPath: '/admin/deleted-users'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminDeletedUsersRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/badges': {
      id: '/_authenticated/_superadmin/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminBadgesRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/audit-log': {
      id: '/_authenticated/_superadmin/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/assembly': {
      id: '/_authenticated/_superadmin/admin/assembly'
      path: '/assembly'
      fullPath: '/admin/assembly'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminAssemblyRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/analytics': {
      id: '/_authenticated/_superadmin/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_superadmin/admin/allowlist': {
      id: '/_authenticated/_superadmin/admin/allowlist'
      path: '/allowlist'
      fullPath: '/admin/allowlist'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminAllowlistRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminRoute
    }
    '/_authenticated/_admin/school/users': {
      id: '/_authenticated/_admin/school/users'
      path: '/users'
      fullPath: '/school/users'
      preLoaderRoute: typeof AuthenticatedAdminSchoolUsersRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_admin/school/updates': {
      id: '/_authenticated/_admin/school/updates'
      path: '/updates'
      fullPath: '/school/updates'
      preLoaderRoute: typeof AuthenticatedAdminSchoolUpdatesRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_admin/school/messages': {
      id: '/_authenticated/_admin/school/messages'
      path: '/messages'
      fullPath: '/school/messages'
      preLoaderRoute: typeof AuthenticatedAdminSchoolMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_admin/school/leaderboard': {
      id: '/_authenticated/_admin/school/leaderboard'
      path: '/leaderboard'
      fullPath: '/school/leaderboard'
      preLoaderRoute: typeof AuthenticatedAdminSchoolLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_admin/school/feed': {
      id: '/_authenticated/_admin/school/feed'
      path: '/feed'
      fullPath: '/school/feed'
      preLoaderRoute: typeof AuthenticatedAdminSchoolFeedRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_admin/school/events': {
      id: '/_authenticated/_admin/school/events'
      path: '/events'
      fullPath: '/school/events'
      preLoaderRoute: typeof AuthenticatedAdminSchoolEventsRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_admin/school/assembly': {
      id: '/_authenticated/_admin/school/assembly'
      path: '/assembly'
      fullPath: '/school/assembly'
      preLoaderRoute: typeof AuthenticatedAdminSchoolAssemblyRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_admin/school/activity': {
      id: '/_authenticated/_admin/school/activity'
      path: '/activity'
      fullPath: '/school/activity'
      preLoaderRoute: typeof AuthenticatedAdminSchoolActivityRouteImport
      parentRoute: typeof AuthenticatedAdminSchoolRoute
    }
    '/_authenticated/_superadmin/admin/schools/': {
      id: '/_authenticated/_superadmin/admin/schools/'
      path: '/'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminSchoolsRoute
    }
    '/_authenticated/_superadmin/admin/schools/pending': {
      id: '/_authenticated/_superadmin/admin/schools/pending'
      path: '/pending'
      fullPath: '/admin/schools/pending'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminSchoolsPendingRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminSchoolsRoute
    }
    '/_authenticated/_admin/admin_/assembly_/present': {
      id: '/_authenticated/_admin/admin_/assembly_/present'
      path: '/admin/assembly/present'
      fullPath: '/admin/assembly/present'
      preLoaderRoute: typeof AuthenticatedAdminAdminAssemblyPresentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminSchoolRouteChildren {
  AuthenticatedAdminSchoolActivityRoute: typeof AuthenticatedAdminSchoolActivityRoute
  AuthenticatedAdminSchoolAssemblyRoute: typeof AuthenticatedAdminSchoolAssemblyRoute
  AuthenticatedAdminSchoolEventsRoute: typeof AuthenticatedAdminSchoolEventsRoute
  AuthenticatedAdminSchoolFeedRoute: typeof AuthenticatedAdminSchoolFeedRoute
  AuthenticatedAdminSchoolLeaderboardRoute: typeof AuthenticatedAdminSchoolLeaderboardRoute
  AuthenticatedAdminSchoolMessagesRoute: typeof AuthenticatedAdminSchoolMessagesRoute
  AuthenticatedAdminSchoolUpdatesRoute: typeof AuthenticatedAdminSchoolUpdatesRoute
  AuthenticatedAdminSchoolUsersRoute: typeof AuthenticatedAdminSchoolUsersRoute
}

const AuthenticatedAdminSchoolRouteChildren: AuthenticatedAdminSchoolRouteChildren =
  {
    AuthenticatedAdminSchoolActivityRoute:
      AuthenticatedAdminSchoolActivityRoute,
    AuthenticatedAdminSchoolAssemblyRoute:
      AuthenticatedAdminSchoolAssemblyRoute,
    AuthenticatedAdminSchoolEventsRoute: AuthenticatedAdminSchoolEventsRoute,
    AuthenticatedAdminSchoolFeedRoute: AuthenticatedAdminSchoolFeedRoute,
    AuthenticatedAdminSchoolLeaderboardRoute:
      AuthenticatedAdminSchoolLeaderboardRoute,
    AuthenticatedAdminSchoolMessagesRoute:
      AuthenticatedAdminSchoolMessagesRoute,
    AuthenticatedAdminSchoolUpdatesRoute: AuthenticatedAdminSchoolUpdatesRoute,
    AuthenticatedAdminSchoolUsersRoute: AuthenticatedAdminSchoolUsersRoute,
  }

const AuthenticatedAdminSchoolRouteWithChildren =
  AuthenticatedAdminSchoolRoute._addFileChildren(
    AuthenticatedAdminSchoolRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSchoolRoute: typeof AuthenticatedAdminSchoolRouteWithChildren
  AuthenticatedAdminAdminAssemblyPresentRoute: typeof AuthenticatedAdminAdminAssemblyPresentRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSchoolRoute: AuthenticatedAdminSchoolRouteWithChildren,
  AuthenticatedAdminAdminAssemblyPresentRoute:
    AuthenticatedAdminAdminAssemblyPresentRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSuperadminAdminSchoolsRouteChildren {
  AuthenticatedSuperadminAdminSchoolsPendingRoute: typeof AuthenticatedSuperadminAdminSchoolsPendingRoute
  AuthenticatedSuperadminAdminSchoolsIndexRoute: typeof AuthenticatedSuperadminAdminSchoolsIndexRoute
}

const AuthenticatedSuperadminAdminSchoolsRouteChildren: AuthenticatedSuperadminAdminSchoolsRouteChildren =
  {
    AuthenticatedSuperadminAdminSchoolsPendingRoute:
      AuthenticatedSuperadminAdminSchoolsPendingRoute,
    AuthenticatedSuperadminAdminSchoolsIndexRoute:
      AuthenticatedSuperadminAdminSchoolsIndexRoute,
  }

const AuthenticatedSuperadminAdminSchoolsRouteWithChildren =
  AuthenticatedSuperadminAdminSchoolsRoute._addFileChildren(
    AuthenticatedSuperadminAdminSchoolsRouteChildren,
  )

interface AuthenticatedSuperadminAdminRouteChildren {
  AuthenticatedSuperadminAdminAllowlistRoute: typeof AuthenticatedSuperadminAdminAllowlistRoute
  AuthenticatedSuperadminAdminAnalyticsRoute: typeof AuthenticatedSuperadminAdminAnalyticsRoute
  AuthenticatedSuperadminAdminAssemblyRoute: typeof AuthenticatedSuperadminAdminAssemblyRoute
  AuthenticatedSuperadminAdminAuditLogRoute: typeof AuthenticatedSuperadminAdminAuditLogRoute
  AuthenticatedSuperadminAdminBadgesRoute: typeof AuthenticatedSuperadminAdminBadgesRoute
  AuthenticatedSuperadminAdminDeletedUsersRoute: typeof AuthenticatedSuperadminAdminDeletedUsersRoute
  AuthenticatedSuperadminAdminEventsRoute: typeof AuthenticatedSuperadminAdminEventsRoute
  AuthenticatedSuperadminAdminHousesRoute: typeof AuthenticatedSuperadminAdminHousesRoute
  AuthenticatedSuperadminAdminInvitesRoute: typeof AuthenticatedSuperadminAdminInvitesRoute
  AuthenticatedSuperadminAdminMediaRoute: typeof AuthenticatedSuperadminAdminMediaRoute
  AuthenticatedSuperadminAdminReportsRoute: typeof AuthenticatedSuperadminAdminReportsRoute
  AuthenticatedSuperadminAdminSchoolsRoute: typeof AuthenticatedSuperadminAdminSchoolsRouteWithChildren
  AuthenticatedSuperadminAdminSettingsRoute: typeof AuthenticatedSuperadminAdminSettingsRoute
  AuthenticatedSuperadminAdminSurveysRoute: typeof AuthenticatedSuperadminAdminSurveysRoute
  AuthenticatedSuperadminAdminUpdatesRoute: typeof AuthenticatedSuperadminAdminUpdatesRoute
  AuthenticatedSuperadminAdminUsersRoute: typeof AuthenticatedSuperadminAdminUsersRoute
  AuthenticatedSuperadminAdminIndexRoute: typeof AuthenticatedSuperadminAdminIndexRoute
}

const AuthenticatedSuperadminAdminRouteChildren: AuthenticatedSuperadminAdminRouteChildren =
  {
    AuthenticatedSuperadminAdminAllowlistRoute:
      AuthenticatedSuperadminAdminAllowlistRoute,
    AuthenticatedSuperadminAdminAnalyticsRoute:
      AuthenticatedSuperadminAdminAnalyticsRoute,
    AuthenticatedSuperadminAdminAssemblyRoute:
      AuthenticatedSuperadminAdminAssemblyRoute,
    AuthenticatedSuperadminAdminAuditLogRoute:
      AuthenticatedSuperadminAdminAuditLogRoute,
    AuthenticatedSuperadminAdminBadgesRoute:
      AuthenticatedSuperadminAdminBadgesRoute,
    AuthenticatedSuperadminAdminDeletedUsersRoute:
      AuthenticatedSuperadminAdminDeletedUsersRoute,
    AuthenticatedSuperadminAdminEventsRoute:
      AuthenticatedSuperadminAdminEventsRoute,
    AuthenticatedSuperadminAdminHousesRoute:
      AuthenticatedSuperadminAdminHousesRoute,
    AuthenticatedSuperadminAdminInvitesRoute:
      AuthenticatedSuperadminAdminInvitesRoute,
    AuthenticatedSuperadminAdminMediaRoute:
      AuthenticatedSuperadminAdminMediaRoute,
    AuthenticatedSuperadminAdminReportsRoute:
      AuthenticatedSuperadminAdminReportsRoute,
    AuthenticatedSuperadminAdminSchoolsRoute:
      AuthenticatedSuperadminAdminSchoolsRouteWithChildren,
    AuthenticatedSuperadminAdminSettingsRoute:
      AuthenticatedSuperadminAdminSettingsRoute,
    AuthenticatedSuperadminAdminSurveysRoute:
      AuthenticatedSuperadminAdminSurveysRoute,
    AuthenticatedSuperadminAdminUpdatesRoute:
      AuthenticatedSuperadminAdminUpdatesRoute,
    AuthenticatedSuperadminAdminUsersRoute:
      AuthenticatedSuperadminAdminUsersRoute,
    AuthenticatedSuperadminAdminIndexRoute:
      AuthenticatedSuperadminAdminIndexRoute,
  }

const AuthenticatedSuperadminAdminRouteWithChildren =
  AuthenticatedSuperadminAdminRoute._addFileChildren(
    AuthenticatedSuperadminAdminRouteChildren,
  )

interface AuthenticatedSuperadminRouteChildren {
  AuthenticatedSuperadminAdminRoute: typeof AuthenticatedSuperadminAdminRouteWithChildren
}

const AuthenticatedSuperadminRouteChildren: AuthenticatedSuperadminRouteChildren =
  {
    AuthenticatedSuperadminAdminRoute:
      AuthenticatedSuperadminAdminRouteWithChildren,
  }

const AuthenticatedSuperadminRouteWithChildren =
  AuthenticatedSuperadminRoute._addFileChildren(
    AuthenticatedSuperadminRouteChildren,
  )

interface AuthenticatedChallengesRouteChildren {
  AuthenticatedChallengesIdRoute: typeof AuthenticatedChallengesIdRoute
  AuthenticatedChallengesMySuggestionsRoute: typeof AuthenticatedChallengesMySuggestionsRoute
}

const AuthenticatedChallengesRouteChildren: AuthenticatedChallengesRouteChildren =
  {
    AuthenticatedChallengesIdRoute: AuthenticatedChallengesIdRoute,
    AuthenticatedChallengesMySuggestionsRoute:
      AuthenticatedChallengesMySuggestionsRoute,
  }

const AuthenticatedChallengesRouteWithChildren =
  AuthenticatedChallengesRoute._addFileChildren(
    AuthenticatedChallengesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRouteWithChildren
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSurveyRoute: typeof AuthenticatedSurveyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSurveyRoute: AuthenticatedSurveyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterSchoolRoute: RegisterSchoolRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinCodeRoute: JoinCodeRoute,
  SchoolsSchoolIdSignupRoute: SchoolsSchoolIdSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
